// This file contains the product data that can be used to seed the Firestore database.
import type { Product } from '@/lib/types';

export const products: Product[] = [
  {
    id: 'classic-leather-tote',
    name: 'Classic Leather Tote',
    description: 'A timeless tote bag crafted from genuine full-grain leather. Spacious enough for your daily essentials, including a 13-inch laptop. Features an interior zip pocket and a magnetic closure.',
    category: 'Bags',
    material: 'Leather',
    color: 'Brown',
    price: 89.82,
    imageUrls: ['https://picsum.photos/seed/1/1000/1000', 'https://picsum.photos/seed/newtote2/1000/1000', 'https://picsum.photos/seed/newtote3/1000/1000', 'https://picsum.photos/seed/newtote4/1000/1000'],
    imageHints: ['leather tote', 'brown tote bag', 'women\'s handbag', 'fashion accessory'],
    sizes: ['One Size'],
    care: ['Wipe clean with a damp cloth.', 'Use a leather conditioner periodically.'],
  },
  {
    id: 'city-slicker-umbrella',
    name: 'City-Slicker Umbrella',
    description: 'Stay dry in style with this compact and durable travel umbrella. Features a wind-resistant frame and an automatic open/close mechanism for easy one-handed operation.',
    category: 'Umbrellas',
    material: 'Pongee Fabric',
    color: 'Charcoal',
    price: 45.0,
    imageUrls: ['https://picsum.photos/seed/2/1000/1000', 'https://picsum.photos/seed/2a/1000/1000', 'https://picsum.photos/seed/2b/1000/1000'],
    imageHints: ['black umbrella', 'open umbrella', 'rain accessory'],
    sizes: ['One Size'],
  },
  {
    id: 'minimalist-cardholder',
    name: 'Minimalist Cardholder',
    description: 'A slim and sleek cardholder for the modern minimalist. Made from premium Italian leather, it features four card slots and a central compartment for folded bills.',
    category: 'Accessories',
    material: 'Leather',
    color: 'Tan',
    price: 75.0,
    imageUrls: ['https://picsum.photos/seed/3/1000/1000', 'https://picsum.photos/seed/3a/1000/1000', 'https://picsum.photos/seed/3b/1000/1000'],
    imageHints: ['leather cardholder', 'wallet', 'minimalist accessory'],
  },
  {
    id: 'merino-wool-scarf',
    name: 'Merino Wool Scarf',
    description: 'Wrap yourself in luxury with this ultra-soft scarf made from 100% merino wool. Its generous size allows for versatile styling, providing both warmth and elegance.',
    category: 'Apparel',
    material: 'Wool',
    color: 'Heather Grey',
    price: 120.0,
    imageUrls: ['https://picsum.photos/seed/4/1000/1000', 'https://picsum.photos/seed/4a/1000/1000', 'https://picsum.photos/seed/4b/1000/1000'],
    imageHints: ['wool scarf', 'grey scarf', 'winter accessory'],
    sizes: ['One Size'],
    care: ['Dry clean only.'],
  },
  {
    id: 'canvas-weekender-bag',
    name: 'Canvas Weekender Bag',
    description: 'The perfect companion for your short getaways. This durable canvas bag is accented with leather details and features a detachable shoulder strap and multiple pockets for organization.',
    category: 'Bags',
    material: 'Canvas',
    color: 'Olive Green',
    price: 180.0,
    imageUrls: ['https://picsum.photos/seed/5/1000/1000', 'https://picsum.photos/seed/5a/1000/1000', 'https://picsum.photos/seed/5b/1000/1000'],
    imageHints: ['canvas bag', 'travel bag', 'weekender tote'],
    sizes: ['One Size'],
  },
  {
    id: 'cashmere-beanie',
    name: 'Cashmere Beanie',
    description: 'A luxuriously soft and warm beanie knitted from pure cashmere. The ribbed cuff ensures a snug and comfortable fit, making it a winter essential.',
    category: 'Apparel',
    material: 'Cashmere',
    color: 'Navy',
    price: 95.0,
    imageUrls: ['https://picsum.photos/seed/6/1000/1000', 'https://picsum.photos/seed/6a/1000/1000', 'https://picsum.photos/seed/6b/1000/1000'],
    imageHints: ['cashmere beanie', 'blue hat', 'winter hat'],
  },
  {
    id: 'the-aviator-sunglasses',
    name: 'The Aviator Sunglasses',
    description: 'Classic aviator sunglasses with a modern twist. Featuring a lightweight metal frame and polarized lenses that provide 100% UV protection.',
    category: 'Accessories',
    material: 'Metal',
    color: 'Gold',
    price: 150.0,
    imageUrls: ['https://picsum.photos/seed/7/1000/1000', 'https://picsum.photos/seed/7a/1000/1000', 'https://picsum.photos/seed/7b/1000/1000'],
    imageHints: ['aviator sunglasses', 'gold sunglasses', 'eyewear'],
  },
  {
    id: 'storm-proof-golf-umbrella',
    name: 'Storm-Proof Golf Umbrella',
    description: 'A large, vented golf umbrella designed to withstand strong winds. The double-canopy design and fiberglass frame offer superior durability on and off the course.',
    category: 'Umbrellas',
    material: 'Nylon',
    color: 'Black',
    price: 65.0,
    imageUrls: ['https://picsum.photos/seed/8/1000/1000', 'https://picsum.photos/seed/8a/1000/1000', 'https://picsum.photos/seed/8b/1000/1000'],
    imageHints: ['golf umbrella', 'large umbrella', 'black umbrella'],
  },
  {
    id: 'suede-belt',
    name: 'Suede Belt',
    description: 'A versatile belt crafted from soft, genuine suede. The brushed silver buckle adds a touch of understated sophistication to both casual and formal outfits.',
    category: 'Accessories',
    material: 'Suede',
    color: 'Chocolate Brown',
    price: 85.0,
    imageUrls: ['https://picsum.photos/seed/9/1000/1000', 'https://picsum.photos/seed/9a/1000/1000', 'https://picsum.photos/seed/9b/1000/1000'],
    imageHints: ['suede belt', 'brown belt', 'leather belt'],
    sizes: ['30', '32', '34', '36', '38'],
  },
  {
    id: 'nylon-backpack',
    name: 'Nylon Backpack',
    description: 'A lightweight and water-resistant backpack designed for the urban commuter. It includes a padded laptop sleeve and multiple organizational pockets.',
    category: 'Bags',
    material: 'Nylon',
    color: 'Black',
    price: 130.0,
    imageUrls: ['https://picsum.photos/seed/10/1000/1000', 'https://picsum.photos/seed/10a/1000/1000', 'https://picsum.photos/seed/10b/1000/1000'],
    imageHints: ['nylon backpack', 'black backpack', 'commuter bag'],
  },
];
