import { FirebaseOptions } from 'firebase/app';

// This file is auto-generated by Firebase Studio. Do not edit.
// Your Firebase project configuration. For more information, see:
// https://firebase.google.com/docs/web/setup#access-firebase

export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyA1uoQ-wzbFvyPkXk5cWZDeQN2TNsVGk2Y",
  authDomain: "studio-1318451066-8d8d0.firebaseapp.com",
  projectId: "studio-1318451066-8d8d0",
  storageBucket: "studio-1318451066-8d8d0.appspot.com",
  messagingSenderId: "660819175294",
  appId: "1:660819175294:web:f9d3b934127bfb0605752f"
};
